### Pasos para ejecutar este archivo

### instala python y demas dependencias 
- instalar python
- instalar python-venv
- instalar python-pip

### crear la carpeta del proyecto y abrirlo en vscode

### activar el entorno virtual
en Linux

 ```bash
python3 -m venv .venv
source .venv/bin/active
```

- crea el entorno virtual
- activalo

deberia aparecer algo como 

```bash
(.venv) usuario@pc:~/Documentos/AprendizajeComp$

```

### instala las dependencias para el notebook

```bash
# Actualizar pip dentro del entorno
python -m pip install --upgrade pip
# Instalar ipykernel (para que el venv pueda ser un kernel de Jupyter)
python -m pip install ipykernel

# registra el kernel con un nombre personalizable
python -m ipykernel install --user \\
  --name=aprendizajecomp \\
  --display-name="Python (AprendizajeComp)"


```

### Instalar dependencias
!pip install pandas numpy matplotlib scikit-learn joblib
Nota ejecutar solo una vez.

In [1]:
!pip install pandas numpy matplotlib scikit-learn joblib

Collecting pandas
  Using cached pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy
  Using cached numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting joblib
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.12/site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Using cached numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Using cached matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
Using cached scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
Using cached kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
Using cached pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached scipy-1.17.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, pyparsing, pillow, numpy, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [matplotlib]7m━━━ 12/13 [matplotlib]n]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 joblib-1.5.3 kiwisolver-1.5.0 matplotlib-3.10.8 numpy-2.4.3 pandas-3.0.1 pillow-12.1.1 pyparsing-3.3.2 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

In [2]:
import pandas as pd
import matplotlib as plt
from sklearn import tree
import numpy as np
from sklearn import tree

In [5]:
wine = pd.read_csv('winequality-red.csv')
wine.head(15)

    fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0             7.4             0.700         0.00  ...       0.56      9.4        5
1             7.8             0.880         0.00  ...       0.68      9.8        5
2             7.8             0.760         0.04  ...       0.65      9.8        5
3            11.2             0.280         0.56  ...       0.58      9.8        6
4             7.4             0.700         0.00  ...       0.56      9.4        5
5             7.4             0.660         0.00  ...       0.56      9.4        5
6             7.9             0.600         0.06  ...       0.46      9.4        5
7             7.3             0.650         0.00  ...       0.47     10.0        7
8             7.8             0.580         0.02  ...       0.57      9.5        7
9             7.5             0.500         0.36  ...       0.80     10.5        5
10            6.7             0.580         0.08  ...       0.54      9.2        5
11            7.5             0.500         0.36  ...       0.80     10.5        5
12            5.6             0.615         0.00  ...       0.52      9.9        5
13            7.8             0.610         0.29  ...       1.56      9.1        5
14            8.9             0.620         0.18  ...       0.88      9.2        5

[15 rows x 12 columns]

In [9]:
wine.quality.value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [10]:
wine.shape

(1599, 12)

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
train, test = train_test_split(wine, test_size=0.30)
train.shape

(1119, 12)

In [14]:
test.shape

(480, 12)

In [15]:
x_train = train[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]
y_train = train['quality']

In [16]:
x_test = test[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']]
y_test = test['quality']

In [17]:
model = tree.DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [18]:
y_pred = model.predict(x_test)
y_pred

array([6, 5, 6, 6, 6, 6, 4, 5, 7, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 7, 7, 6,
       5, 6, 5, 6, 6, 5, 6, 6, 5, 4, 6, 6, 7, 5, 5, 6, 7, 6, 6, 5, 5, 6,
       6, 6, 4, 6, 5, 5, 5, 5, 7, 7, 6, 6, 6, 7, 6, 5, 5, 7, 5, 7, 5, 5,
       6, 5, 5, 7, 5, 7, 7, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 7, 5, 5, 6, 7,
       6, 5, 5, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 7, 6, 6, 5, 7, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6,
       5, 5, 5, 6, 5, 6, 6, 5, 5, 5, 7, 5, 7, 6, 5, 5, 6, 5, 4, 5, 5, 6,
       7, 6, 5, 5, 7, 6, 6, 3, 5, 6, 6, 5, 5, 5, 6, 7, 5, 7, 7, 5, 6, 5,
       6, 5, 5, 6, 6, 5, 4, 6, 5, 6, 5, 7, 7, 6, 7, 7, 5, 5, 4, 6, 5, 5,
       6, 6, 5, 6, 7, 7, 7, 6, 7, 6, 5, 6, 7, 5, 6, 7, 5, 6, 7, 5, 6, 5,
       5, 4, 7, 5, 6, 5, 5, 6, 7, 5, 6, 5, 6, 5, 5, 7, 6, 5, 6, 6, 7, 6,
       6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 6, 7, 5, 5, 6, 6, 6, 5, 5,
       6, 7, 7, 5, 5, 6, 6, 5, 6, 7, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6,
       6, 7, 7, 6, 5, 5, 6, 7, 5, 6, 6, 6, 6, 5, 5, 7, 5, 5, 6, 5, 5, 6,
       5, 4, 6, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 6, 7, 5,
       5, 5, 7, 5, 5, 6, 6, 6, 7, 6, 6, 6, 5, 5, 5, 7, 6, 7, 5, 6, 5, 5,
       6, 6, 7, 6, 6, 5, 6, 6, 5, 4, 6, 6, 7, 6, 6, 7, 5, 6, 5, 7, 5, 5,
       6, 5, 5, 4, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 7, 6, 5, 5, 5,
       7, 5, 5, 6, 6, 6, 7, 5, 5, 6, 6, 6, 5, 5, 6, 7, 7, 6, 7, 6, 5, 5,
       6, 6, 5, 5, 5, 5, 4, 5, 5, 6, 6, 5, 6, 7, 6, 5, 8, 6, 5, 6, 6, 6,
       6, 7, 5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 7,
       6, 5, 7, 6, 6, 6, 5, 5, 6, 6, 7, 5, 7, 7, 5, 5, 6, 6])

In [20]:
df_prediccion = pd.DataFrame(y_pred)
df_prediccion['real']=y_test.values
df_prediccion.head(10)

   0  real
0  6     6
1  5     5
2  6     5
3  6     6
4  6     5
5  6     4
6  4     5
7  5     5
8  7     6
9  6     5

In [21]:
model.score(x_test, y_test)*100

61.04166666666667

* el modelo tuvo un 61% de efectividad toca balancearlo o cambiar de modelo.